version: '3'
services:
  app:
    image: 'ghcr.io/edcharbeneau/powerproduction:latest'
    restart: unless-stopped
    ports:
      - '8080:8080'  # host-port:container-port
    environment:
      - MQTT_HOST=""  # Your-mqtt-server's ip-address or-domain name
      - MQTT_PORT=""  # This is 1883 by default, but some domain-based servers just serve over 80 (http) or 443 (https).