name: Main

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    paths:
      - 'BlazorSolarPowerHour/**/*'
      - '.github/workflows/master.yml'
  push:
    branches:
      - master
    paths:
      - 'BlazorSolarPowerHour/**/*'
      - '.github/workflows/master.yml'

permissions:
  id-token: write # OIDC token permissions for AKeyless
  contents: read

env:
  PROJECT_PATH: 'BlazorSolarPowerHour\BlazorSolarPowerHour.csproj'
  DOTNETVER: '10.0.*'

jobs:
  build_windows: # quick debug build on Windows, no publishing (see releases.yml for deployments)
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{env.DOTNETVER}}

    - name: Fetch secrets from AKeyless
      id: akeyless
      uses: LanceMcCarthy/akeyless-action@v5
      with:
        access-id: "p-fq3qbjjxv839"
        static-secrets: '{"/personal-keys/mccarthy/TELERIK_NUGET_KEY":"TELERIK_NUGET_KEY", "/personal-keys/mccarthy/TELERIK_LICENSE":"LICENSE_KEY"}'
        export-secrets-to-outputs: true
        export-secrets-to-environment: false

    - name: Add Telerik NuGet Package Source
      run: dotnet nuget add source 'https://nuget.telerik.com/v3/index.json' -n "TelerikNuGetServer" -u "api-key" -p ${{steps.akeyless.outputs.TELERIK_NUGET_KEY}} --store-password-in-clear-text
    
    - name: Restore NuGet Packages
      run: dotnet restore ${{env.PROJECT_PATH}}

    - name: Build Project
      run: dotnet build ${{env.PROJECT_PATH}} -c Release --no-restore
      env:
        TELERIK_LICENSE: ${{steps.akeyless.outputs.LICENSE_KEY}}